# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a22acb97db04f7fec6b4bc31918525bea7e5b63d51e66e6eea4cd5020b9a67ce2dd2305111b1976792a3104c59da004f3ee4e3f6c59784a52304cad04b9a14b

test:
  secret_key_base: 1257fef06ee6445efb2fb178d28d2d5f9c080406e27f76caa9abd1bc95049b2a22853097be2fe80cf93580f603fa7d4e118acffc10bdfd950cc07844993da4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
